default: &default
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: abhizone_dev

staging:
  <<: *default
  database: abhizone_stag

test:
  <<: *default
  database: abhizone_test

production:
  <<: *default
  database: abhizone_prod
